-- stops of the transit network
create table if not exists public.stops (
  id                    bigint generated by default as identity primary key,
  name                  varchar(255) not null,
  lines                 varchar(255) not null default '', -- lines serving the stop, as "A;B"
  is_transfer           boolean not null default false,
  transfer_lines        varchar(255),                     -- lines you can transfer to, as "A;B"
  x                     double precision not null,        -- horizontal position
  y                     double precision not null,        -- vertical position
  wheelchair_accessible boolean not null default false,   -- step-free
  has_shelter           boolean not null default false,
  has_bench             boolean not null default false,
  has_ticket_machine    boolean not null default false,
  has_display           boolean not null default false,   -- information display
  image_url             varchar(255)
);

-- anyone can read stops
alter table public.stops enable row level security;

create policy "stops are readable by everyone"
  on public.stops for select
  using (true);
